package br.com.matheusbodo.rspt.layout;

import org.tepi.filtertable.FilterTable;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FontAwesome;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

public class CustomersLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private FilterTable tableCustomers;

	@AutoGenerated
	private Button btnNovo;

	@AutoGenerated
	private Label line;

	@AutoGenerated
	private Label labelClientes;

	private static final long serialVersionUID = -4960431791506727546L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CustomersLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		labelClientes.addStyleName(ValoTheme.LABEL_H2);
		
		line.setValue("<hr/>");
		line.setContentMode(ContentMode.HTML);
		
		btnNovo.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		btnNovo.setIcon(FontAwesome.PLUS);
		
		tableCustomers.addStyleName(ValoTheme.TABLE_COMPACT);
		
		tableCustomers.setFilterBarVisible(true);
		tableCustomers.setSelectable(true);
	}
	
	public FilterTable getTableCustomers() {
		return tableCustomers;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// labelClientes
		labelClientes = new Label();
		labelClientes.setImmediate(false);
		labelClientes.setWidth("-1px");
		labelClientes.setHeight("-1px");
		labelClientes.setValue("Cadastro de Clientes");
		mainLayout.addComponent(labelClientes);
		
		// line
		line = new Label();
		line.setImmediate(false);
		line.setWidth("-1px");
		line.setHeight("-1px");
		line.setValue("Label");
		mainLayout.addComponent(line);
		
		// btnNovo
		btnNovo = new Button();
		btnNovo.setCaption("Novo");
		btnNovo.setImmediate(true);
		btnNovo.setWidth("-1px");
		btnNovo.setHeight("-1px");
		mainLayout.addComponent(btnNovo);
		mainLayout.setComponentAlignment(btnNovo, new Alignment(6));
		
		// tableCustomers
		tableCustomers = new FilterTable();
		tableCustomers.setImmediate(false);
		tableCustomers.setWidth("100.0%");
		tableCustomers.setHeight("-1px");
		mainLayout.addComponent(tableCustomers);
		mainLayout.setExpandRatio(tableCustomers, 1.0f);
		
		return mainLayout;
	}
	
	public void addNewButtonClickListener(ClickListener listener) {
		btnNovo.addClickListener(listener);
	}

}
