package br.com.matheusbodo.rspt.layout;

import lombok.Getter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@Getter
public class EditProfileLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = -8872286513115751756L;
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button btnDeleteAccount;
	@AutoGenerated
	private Button btnResetData;
	@AutoGenerated
	private Button btnChangePassword;
	@AutoGenerated
	private Label lblUser;
	@AutoGenerated
	private Label lblTitle;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EditProfileLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		lblTitle.addStyleName(ValoTheme.LABEL_H1);
		lblUser.addStyleName(ValoTheme.LABEL_BOLD);
		
		btnChangePassword.addStyleName(ValoTheme.BUTTON_PRIMARY);
		btnResetData.addStyleName(ValoTheme.BUTTON_DANGER);
		btnDeleteAccount.addStyleName(ValoTheme.BUTTON_DANGER);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		mainLayout.addComponent(verticalLayout_2);
		mainLayout.setComponentAlignment(verticalLayout_2, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("400px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		verticalLayout_2.setSpacing(true);
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("Edit Profile");
		verticalLayout_2.addComponent(lblTitle);
		verticalLayout_2.setComponentAlignment(lblTitle, new Alignment(20));
		
		// lblUser
		lblUser = new Label();
		lblUser.setImmediate(false);
		lblUser.setWidth("-1px");
		lblUser.setHeight("-1px");
		lblUser.setValue("userEmail");
		verticalLayout_2.addComponent(lblUser);
		verticalLayout_2.setComponentAlignment(lblUser, new Alignment(20));
		
		// btnChangePassword
		btnChangePassword = new Button();
		btnChangePassword.setCaption("Change Password");
		btnChangePassword.setImmediate(false);
		btnChangePassword.setWidth("80.0%");
		btnChangePassword.setHeight("-1px");
		verticalLayout_2.addComponent(btnChangePassword);
		verticalLayout_2.setComponentAlignment(btnChangePassword,
				new Alignment(20));
		
		// btnResetData
		btnResetData = new Button();
		btnResetData.setCaption("Reset All Data");
		btnResetData.setImmediate(false);
		btnResetData.setWidth("80.0%");
		btnResetData.setHeight("-1px");
		verticalLayout_2.addComponent(btnResetData);
		verticalLayout_2.setComponentAlignment(btnResetData, new Alignment(20));
		
		// btnDeleteAccount
		btnDeleteAccount = new Button();
		btnDeleteAccount.setCaption("Delete Account");
		btnDeleteAccount.setImmediate(false);
		btnDeleteAccount.setWidth("80.0%");
		btnDeleteAccount.setHeight("-1px");
		verticalLayout_2.addComponent(btnDeleteAccount);
		verticalLayout_2.setComponentAlignment(btnDeleteAccount, new Alignment(
				20));
		
		return verticalLayout_2;
	}

}
