package br.com.matheusbodo.rspt.layout;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

public class HomeLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = -759413864121348782L;
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Label lblWelcomeMessage;
	@AutoGenerated
	private Label lblTitle;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HomeLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		lblTitle.addStyleName(ValoTheme.LABEL_H1);
		lblWelcomeMessage.addStyleName(ValoTheme.LABEL_BOLD);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("Rocksmith Practice Tracker");
		mainLayout.addComponent(lblTitle);
		mainLayout.setComponentAlignment(lblTitle, new Alignment(20));
		
		// lblWelcomeMessage
		lblWelcomeMessage = new Label();
		lblWelcomeMessage.setImmediate(false);
		lblWelcomeMessage.setWidth("500px");
		lblWelcomeMessage.setHeight("-1px");
		lblWelcomeMessage
				.setValue("Welcome to Rocksmith Practice tracker.  Here you can track your progress on Rocksmith!! Log your sessions and see statistics about your progress.");
		mainLayout.addComponent(lblWelcomeMessage);
		mainLayout.setComponentAlignment(lblWelcomeMessage, new Alignment(20));
		
		return mainLayout;
	}

}
