package br.com.matheusbodo.rspt.layout;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class LoginLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 4238732453085143189L;
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout formPanel;
	@AutoGenerated
	private Button btnLogin;
	@AutoGenerated
	private PasswordField fieldPassword;
	@AutoGenerated
	private TextField fieldLogin;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		formPanel.addStyleName("login-box");
	}
	
	public Button getBtnLogin() {
		return btnLogin;
	}
	
	public TextField getFieldLogin() {
		return fieldLogin;
	}
	
	public PasswordField getFieldPassword() {
		return fieldPassword;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// formPanel
		formPanel = buildFormPanel();
		mainLayout.addComponent(formPanel);
		mainLayout.setComponentAlignment(formPanel, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildFormPanel() {
		// common part: create layout
		formPanel = new VerticalLayout();
		formPanel.setImmediate(false);
		formPanel.setWidth("-1px");
		formPanel.setHeight("-1px");
		formPanel.setMargin(true);
		formPanel.setSpacing(true);
		
		// fieldLogin
		fieldLogin = new TextField();
		fieldLogin.setCaption("Login");
		fieldLogin.setImmediate(false);
		fieldLogin.setWidth("-1px");
		fieldLogin.setHeight("-1px");
		formPanel.addComponent(fieldLogin);
		
		// fieldPassword
		fieldPassword = new PasswordField();
		fieldPassword.setCaption("Password");
		fieldPassword.setImmediate(false);
		fieldPassword.setWidth("-1px");
		fieldPassword.setHeight("-1px");
		formPanel.addComponent(fieldPassword);
		
		// button_1
		btnLogin = new Button();
		btnLogin.setCaption("Login");
		btnLogin.setImmediate(true);
		btnLogin.setWidth("-1px");
		btnLogin.setHeight("-1px");
		formPanel.addComponent(btnLogin);
		formPanel.setComponentAlignment(btnLogin, new Alignment(20));
		
		return formPanel;
	}

}
