package br.com.matheusbodo.rspt.layout;

import java.util.Arrays;

import lombok.Getter;

import org.tepi.filtertable.paged.PagedFilterControlConfig;
import org.tepi.filtertable.paged.PagedFilterTable;

import br.com.matheusbodo.rspt.entity.enums.Role;
import br.com.matheusbodo.rspt.layout.generator.EditUserButtonGenerator;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@Getter
public class ManageUsersLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	@SuppressWarnings("rawtypes")
	private PagedFilterTable tbUsers;

	@AutoGenerated
	private Button btnNewUser;

	@AutoGenerated
	private Label lblTitle;

	private static final long serialVersionUID = 4502510763096522780L;
	
	private PagedFilterControlConfig tableConfig;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param editUserButtonGenerator 
	 */
	public ManageUsersLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		lblTitle.addStyleName(ValoTheme.LABEL_H1);
		btnNewUser.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		
		tbUsers.setFilterBarVisible(true);
		tbUsers.addContainerProperty("id", String.class, null);
		tbUsers.setColumnHeader("id", "ID");
		tbUsers.addContainerProperty("email", String.class, null);
		tbUsers.setColumnHeader("email", "E-mail");
		tbUsers.addContainerProperty("role", Role.class, null);
		tbUsers.setColumnHeader("role", "Role");
		
		tbUsers.addContainerProperty("edit", HorizontalLayout.class, null);
		tbUsers.setColumnHeader("edit", "");
		
		tbUsers.setFilterBarVisible(true);
		tbUsers.setPageLength(15);
		tableConfig = new PagedFilterControlConfig();
		tableConfig.setPageLengthsAndCaptions(Arrays.asList(10, 20, 50));
		mainLayout.addComponent(tbUsers.createControls(tableConfig));
	}

	@AutoGenerated
	@SuppressWarnings("rawtypes")
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("Manage Users");
		mainLayout.addComponent(lblTitle);
		mainLayout.setComponentAlignment(lblTitle, new Alignment(20));
		
		// btnNewUser
		btnNewUser = new Button();
		btnNewUser.setCaption("Add User");
		btnNewUser.setImmediate(true);
		btnNewUser.setWidth("-1px");
		btnNewUser.setHeight("-1px");
		mainLayout.addComponent(btnNewUser);
		mainLayout.setComponentAlignment(btnNewUser, new Alignment(6));
		
		// tbUsers
		tbUsers = new PagedFilterTable();
		tbUsers.setImmediate(false);
		tbUsers.setWidth("100.0%");
		tbUsers.setHeight("-1px");
		mainLayout.addComponent(tbUsers);
		
		return mainLayout;
	}

}
