package br.com.matheusbodo.rspt.layout;

import lombok.Getter;
import lombok.Setter;
import br.com.matheusbodo.rspt.entity.enums.GuitarcadeGame;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@Getter
@Setter
public class PracticeGuitarcadeLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private VerticalLayout verticalLayout_1;

	@AutoGenerated
	private Button btnSave;

	@AutoGenerated
	private TextField fieldMinutes;

	@AutoGenerated
	private TextField fieldScore;

	@AutoGenerated
	private ComboBox comboGames;

	@AutoGenerated
	private Label lblPracticeGuitarcade;

	private static final long serialVersionUID = -5169995683845005195L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PracticeGuitarcadeLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		lblPracticeGuitarcade.addStyleName(ValoTheme.LABEL_H1);
		btnSave.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		
		fieldMinutes.setNullRepresentation("");
		fieldScore.setNullRepresentation("");
		
		for (GuitarcadeGame game : GuitarcadeGame.values()) {
			comboGames.addItem(game);
			comboGames.setItemCaption(game, game.getCaption());
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1);
		mainLayout.setComponentAlignment(verticalLayout_1, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("250px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);
		verticalLayout_1.setSpacing(true);
		
		// lblPracticeGuitarcade
		lblPracticeGuitarcade = new Label();
		lblPracticeGuitarcade.setImmediate(false);
		lblPracticeGuitarcade.setWidth("-1px");
		lblPracticeGuitarcade.setHeight("-1px");
		lblPracticeGuitarcade.setValue("Practice Guitarcade");
		verticalLayout_1.addComponent(lblPracticeGuitarcade);
		verticalLayout_1.setComponentAlignment(lblPracticeGuitarcade,
				new Alignment(20));
		
		// comboGames
		comboGames = new ComboBox();
		comboGames.setCaption("Choose Game:");
		comboGames.setImmediate(true);
		comboGames.setWidth("100.0%");
		comboGames.setHeight("-1px");
		verticalLayout_1.addComponent(comboGames);
		
		// fieldScore
		fieldScore = new TextField();
		fieldScore.setCaption("Score");
		fieldScore.setImmediate(true);
		fieldScore.setWidth("100.0%");
		fieldScore.setHeight("-1px");
		verticalLayout_1.addComponent(fieldScore);
		
		// fieldMinutes
		fieldMinutes = new TextField();
		fieldMinutes.setCaption("Minutes Practiced");
		fieldMinutes.setImmediate(true);
		fieldMinutes.setWidth("100.0%");
		fieldMinutes.setHeight("-1px");
		verticalLayout_1.addComponent(fieldMinutes);
		
		// btnSave
		btnSave = new Button();
		btnSave.setCaption("Save");
		btnSave.setImmediate(true);
		btnSave.setWidth("-1px");
		btnSave.setHeight("-1px");
		verticalLayout_1.addComponent(btnSave);
		verticalLayout_1.setComponentAlignment(btnSave, new Alignment(20));
		
		return verticalLayout_1;
	}

}
