package br.com.matheusbodo.rspt.layout;

import java.math.BigDecimal;

import lombok.Getter;
import lombok.Setter;
import br.com.matheusbodo.rspt.entity.enums.GamePath;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@Getter
@Setter
public class PracticeLearnSongLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private VerticalLayout verticalLayout_1;

	@AutoGenerated
	private Button btnSave;

	@AutoGenerated
	private TextField fieldMinutes;

	@AutoGenerated
	private TextField fieldAccuracy;

	@AutoGenerated
	private TextField fieldCompleted;

	@AutoGenerated
	private ComboBox comboPath;

	@AutoGenerated
	private ComboBox comboSongs;

	@AutoGenerated
	private Label lblPracticeLearnSong;

	private static final long serialVersionUID = -5169995683845005195L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PracticeLearnSongLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		lblPracticeLearnSong.addStyleName(ValoTheme.LABEL_H1);
		btnSave.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		
		fieldMinutes.setNullRepresentation("");
		fieldAccuracy.setNullRepresentation("");
		fieldAccuracy.setConverter(BigDecimal.class);
		fieldCompleted.setNullRepresentation("");
		fieldCompleted.setConverter(BigDecimal.class);
		
		for (GamePath path : GamePath.values()) {
			comboPath.addItem(path);
			comboPath.setItemCaption(path, path.name());
		}
		
		comboSongs.setFilteringMode(FilteringMode.CONTAINS);
		comboPath.setFilteringMode(FilteringMode.CONTAINS);
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1);
		mainLayout.setComponentAlignment(verticalLayout_1, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("250px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);
		verticalLayout_1.setSpacing(true);
		
		// lblPracticeLearnSong
		lblPracticeLearnSong = new Label();
		lblPracticeLearnSong.setImmediate(false);
		lblPracticeLearnSong.setWidth("-1px");
		lblPracticeLearnSong.setHeight("-1px");
		lblPracticeLearnSong.setValue("Practice Learn a Song");
		verticalLayout_1.addComponent(lblPracticeLearnSong);
		verticalLayout_1.setComponentAlignment(lblPracticeLearnSong,
				new Alignment(20));
		
		// comboSongs
		comboSongs = new ComboBox();
		comboSongs.setCaption("Choose Song:");
		comboSongs.setImmediate(true);
		comboSongs.setWidth("100.0%");
		comboSongs.setHeight("-1px");
		verticalLayout_1.addComponent(comboSongs);
		
		// comboPath
		comboPath = new ComboBox();
		comboPath.setCaption("Choose Path:");
		comboPath.setImmediate(true);
		comboPath.setWidth("100.0%");
		comboPath.setHeight("-1px");
		verticalLayout_1.addComponent(comboPath);
		
		// fieldCompleted
		fieldCompleted = new TextField();
		fieldCompleted.setCaption("% Competed");
		fieldCompleted.setImmediate(true);
		fieldCompleted.setWidth("100.0%");
		fieldCompleted.setHeight("-1px");
		verticalLayout_1.addComponent(fieldCompleted);
		
		// fieldAccuracy
		fieldAccuracy = new TextField();
		fieldAccuracy.setCaption("% Accuracy");
		fieldAccuracy.setImmediate(true);
		fieldAccuracy.setWidth("100.0%");
		fieldAccuracy.setHeight("-1px");
		verticalLayout_1.addComponent(fieldAccuracy);
		
		// fieldMinutes
		fieldMinutes = new TextField();
		fieldMinutes.setCaption("Minutes Practiced");
		fieldMinutes.setImmediate(true);
		fieldMinutes.setWidth("100.0%");
		fieldMinutes.setHeight("-1px");
		verticalLayout_1.addComponent(fieldMinutes);
		
		// btnSave
		btnSave = new Button();
		btnSave.setCaption("Save");
		btnSave.setImmediate(true);
		btnSave.setWidth("-1px");
		btnSave.setHeight("-1px");
		verticalLayout_1.addComponent(btnSave);
		verticalLayout_1.setComponentAlignment(btnSave, new Alignment(20));
		
		return verticalLayout_1;
	}

}
