package br.com.matheusbodo.rspt.layout;

import lombok.Getter;
import br.com.matheusbodo.rspt.entity.enums.Role;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@Getter
public class UserFormLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout layoutButtons;

	@AutoGenerated
	private Button btnCancel;

	@AutoGenerated
	private Button btnSave;

	@AutoGenerated
	private FormLayout formLayout;

	@AutoGenerated
	private ComboBox comboRole;

	@AutoGenerated
	private TextField fieldEmail;

	@AutoGenerated
	private Label lblTitle;

	private static final long serialVersionUID = 879774620663014619L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UserFormLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		lblTitle.addStyleName(ValoTheme.LABEL_H1);
		
		btnSave.addStyleName(ValoTheme.BUTTON_FRIENDLY);
		
		fieldEmail.setNullRepresentation("");
		comboRole.addItem(Role.USER);
		comboRole.setItemCaption(Role.USER, "User");
		comboRole.addItem(Role.ADMIN);
		comboRole.setItemCaption(Role.ADMIN, "Admin");
		
		btnCancel.addClickListener(new ClickListener() {
			private static final long serialVersionUID = 7004401037805139272L;
			@Override
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().getNavigator().navigateTo("manageUsers");
			}
		});
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("User");
		mainLayout.addComponent(lblTitle);
		mainLayout.setComponentAlignment(lblTitle, new Alignment(20));
		
		// formLayout
		formLayout = buildFormLayout();
		mainLayout.addComponent(formLayout);
		mainLayout.setComponentAlignment(formLayout, new Alignment(20));
		
		// layoutButtons
		layoutButtons = buildLayoutButtons();
		mainLayout.addComponent(layoutButtons);
		mainLayout.setComponentAlignment(layoutButtons, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private FormLayout buildFormLayout() {
		// common part: create layout
		formLayout = new FormLayout();
		formLayout.setImmediate(false);
		formLayout.setWidth("400px");
		formLayout.setHeight("-1px");
		formLayout.setMargin(false);
		formLayout.setSpacing(true);
		
		// fieldEmail
		fieldEmail = new TextField();
		fieldEmail.setCaption("E-mail");
		fieldEmail.setImmediate(true);
		fieldEmail.setWidth("100.0%");
		fieldEmail.setHeight("-1px");
		formLayout.addComponent(fieldEmail);
		
		// comboRole
		comboRole = new ComboBox();
		comboRole.setCaption("Role");
		comboRole.setImmediate(false);
		comboRole.setWidth("-1px");
		comboRole.setHeight("-1px");
		formLayout.addComponent(comboRole);
		
		return formLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildLayoutButtons() {
		// common part: create layout
		layoutButtons = new HorizontalLayout();
		layoutButtons.setImmediate(false);
		layoutButtons.setWidth("-1px");
		layoutButtons.setHeight("-1px");
		layoutButtons.setMargin(false);
		
		// btnSave
		btnSave = new Button();
		btnSave.setCaption("Salvar");
		btnSave.setImmediate(true);
		btnSave.setWidth("-1px");
		btnSave.setHeight("-1px");
		layoutButtons.addComponent(btnSave);
		
		// btnCancel
		btnCancel = new Button();
		btnCancel.setCaption("Cancelar");
		btnCancel.setImmediate(true);
		btnCancel.setWidth("-1px");
		btnCancel.setHeight("-1px");
		layoutButtons.addComponent(btnCancel);
		
		return layoutButtons;
	}

}
